
import java.awt.Component;
import java.util.Observer;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Coca
 */
public class Menu extends javax.swing.JFrame {
    public static int tiempoInventario;
    public static int tiempoProduccion;
    public static int tiempoEmpaquetado;
    public static int tiempoSalida;
    public static int costoInventario;
    public static int costoProduccion;
    public static int costoEmpaquetado;
    public static int costoSalida;
    private Component Menu;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtTiempoInventario = new javax.swing.JTextField();
        jtxtCostoInventario = new javax.swing.JTextField();
        jtxtTiempoProduccion = new javax.swing.JTextField();
        jtxtCostoProduccion = new javax.swing.JTextField();
        jtxtTiempoEmpaquetado = new javax.swing.JTextField();
        jtxtCostoEmpaquetado = new javax.swing.JTextField();
        jtxtTiempoSalida = new javax.swing.JTextField();
        jtxtCostoSalida = new javax.swing.JTextField();
        jBtmIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MONKEY");
        setBounds(new java.awt.Rectangle(500, 200, 0, 0));

        jLabel1.setText("jLabel1");

        jLabel2.setText("Inventario");

        jLabel3.setText("Tiempo (s)");

        jLabel4.setText("Costo (Q/s)");

        jLabel5.setText("Produccion");

        jLabel6.setText("Empaquetado");

        jLabel7.setText("Salida");

        jBtmIniciar.setText("Iniciar Simulacion");
        jBtmIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtmIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtTiempoProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jtxtTiempoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtTiempoEmpaquetado, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtTiempoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtCostoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtCostoProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCostoEmpaquetado, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCostoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jBtmIniciar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtTiempoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCostoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtTiempoProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCostoProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtTiempoEmpaquetado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCostoEmpaquetado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtTiempoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCostoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jBtmIniciar)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtmIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtmIniciarActionPerformed
        // TODO add your handling code here:
        //declaracion de variables para capturar los datos de la caja de texto
        String datoTiempoInventario=jtxtTiempoInventario.getText();
        String datoTiempoProduccion=jtxtTiempoProduccion.getText();
        String datoTiempoEmpaquetado=jtxtTiempoEmpaquetado.getText();
        String datoTiempoSalida=jtxtTiempoSalida.getText();
        String datoCostoInventario=jtxtCostoInventario.getText();
        String datoCostoProduccion=jtxtCostoProduccion.getText();
        String datoCostoEmpaquetado=jtxtCostoEmpaquetado.getText();
        String datoCostoSalida=jtxtCostoSalida.getText();
            //int tiempoInventario=jtxtTiempoInventario.getText();
            if ((datoTiempoInventario.equals(""))||(datoTiempoProduccion.equals(""))||(datoTiempoEmpaquetado.equals(""))||(datoTiempoSalida.equals(""))||(datoCostoInventario.equals(""))||(datoTiempoProduccion.equals(""))||(datoTiempoEmpaquetado.equals(""))||(datoCostoSalida.equals(""))) {
//            JOptionPane.showMessageDialog(Menu,"Datos correctos");
            System.out.println("Por favor, llene todos los campos");
            JOptionPane.showMessageDialog(Menu,"Por favor, llene todos los campos");
        } else {
            
            try{
                System.out.println("Verificando que sean numeros enteros");
                System.out.println("---------------------------------------------");
                 tiempoInventario=Integer.parseInt(datoTiempoInventario);
                tiempoProduccion=Integer.parseInt(datoTiempoProduccion);
                 tiempoEmpaquetado=Integer.parseInt(datoTiempoEmpaquetado);
                 tiempoSalida=Integer.parseInt(datoTiempoSalida);
                costoInventario=Integer.parseInt(datoCostoInventario);
                costoProduccion=Integer.parseInt(datoCostoProduccion);
                 costoEmpaquetado=Integer.parseInt(datoCostoEmpaquetado);
                 costoSalida=Integer.parseInt(datoCostoSalida);
                if(tiempoInventario>=0 & tiempoProduccion>=0 & tiempoEmpaquetado>=0 & tiempoSalida>=0 & costoInventario>=0 & costoProduccion>=0 & costoEmpaquetado>=0 & costoSalida>=0){
                    JOptionPane.showMessageDialog(Menu,"BIENVENIDO");
                    System.out.println(tiempoInventario);
                    System.out.println(tiempoProduccion);
                    System.out.println(tiempoEmpaquetado);
                    System.out.println(tiempoSalida);
                    System.out.println(costoInventario);
                    System.out.println(costoProduccion);
                    System.out.println(costoEmpaquetado);
                    System.out.println(costoSalida);
                    
                    //Muestra la ventana de proceso
                    Proceso newframe = new Proceso();
                    newframe.setVisible(true);
                    this.dispose();
                    
                    
                }else{
                    System.out.println("Ingrese valores numericos mayores a 0");
                    JOptionPane.showMessageDialog(Menu,"Ingrese valores numericos mayores a 0");
                }
            }catch(NumberFormatException e){
                System.out.println("Ingrese valores numericos y Enteros");
                JOptionPane.showMessageDialog(Menu, "Ingrese valores numericos y Enteros");
            }       
        } 
            
            
            
    }//GEN-LAST:event_jBtmIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtmIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jtxtCostoEmpaquetado;
    private javax.swing.JTextField jtxtCostoInventario;
    private javax.swing.JTextField jtxtCostoProduccion;
    private javax.swing.JTextField jtxtCostoSalida;
    private javax.swing.JTextField jtxtTiempoEmpaquetado;
    private javax.swing.JTextField jtxtTiempoInventario;
    private javax.swing.JTextField jtxtTiempoProduccion;
    private javax.swing.JTextField jtxtTiempoSalida;
    // End of variables declaration//GEN-END:variables

    private static class InputMismatch {

        public InputMismatch() {
        }
    }
}
